# Generated by Django 3.2.6 on 2021-09-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210901_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.ImageField(default='/static/feed/images/night-street.jpg', upload_to='images'),
        ),
    ]
