# Generated by Django 3.2.6 on 2021-09-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210901_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='src',
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(default='night-street.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
