# Generated by Django 3.2.6 on 2021-09-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20210901_0538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(default='/media//night-street.jpg', upload_to='images'),
        ),
    ]
