# Generated by Django 3.2.6 on 2021-09-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210901_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
