# Generated by Django 3.2.6 on 2021-09-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='src',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to='images'),
        ),
    ]
