# Generated by Django 3.2.6 on 2021-09-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
