# Generated by Django 3.2.6 on 2021-09-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20210902_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
